### ISSUE TITLE
Update RuntimeException

### ISSUE THREAD

**Issue by bitsmakerde** [discordier/justtextwidgets#4]
Hi,

ich versuche gerade ein update von 0.5.4 aud 1.0.0 bzw 1.1.1 durch zuführen aber Lider kommt jedes mal über composer folgender Fehler:

- Updating discordier/justtextwidgets (0.5.4 => 1.0.0): Downloading (100%)         

                                                                                                                                   
  [RuntimeException]                                                                                                               
  /www/htdocs/w00c3639/janweylcom_backup_190518/system/modules/justtextwidgets/templates does not exist and could not be created.

**Comment by discordier** [comment]
There seems to be a problem in your installation then.
Apparently the named directory could not be created, this is not a problem in my extension though.
